#ifndef _ALTERA_PLASMA_DE1_SOC_SYSTEM_H_
#define _ALTERA_PLASMA_DE1_SOC_SYSTEM_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'de1_soc' in
 * file '../../proj/quartus/de1_soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'plasma_soc_0', class 'plasma_soc'
 * The macros are prefixed with 'PLASMA_SOC_0_'.
 * The prefix is the slave descriptor.
 */
#define PLASMA_SOC_0_COMPONENT_TYPE plasma_soc
#define PLASMA_SOC_0_COMPONENT_NAME plasma_soc_0
#define PLASMA_SOC_0_BASE 0x0
#define PLASMA_SOC_0_SPAN 536870912
#define PLASMA_SOC_0_END 0x1fffffff

/*
 * Macros for device 'sysid_qsys_0', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_0_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_0_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_0_COMPONENT_NAME sysid_qsys_0
#define SYSID_QSYS_0_BASE 0x0
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_END 0x7
#define SYSID_QSYS_0_ID 3735928559
#define SYSID_QSYS_0_TIMESTAMP 1536706156


#endif /* _ALTERA_PLASMA_DE1_SOC_SYSTEM_H_ */
