// de1_soc_mm_interconnect_3.v

// This file was auto-generated from altera_merlin_interconnect_wrapper_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 162 at 2018.09.05.17:40:17

`timescale 1 ps / 1 ps
module de1_soc_mm_interconnect_3 (
		input  wire         pll_0_outclk0_clk,                                   //                                 pll_0_outclk0.clk
		input  wire         hps_to_plasma_dma_reset_reset_bridge_in_reset_reset, // hps_to_plasma_dma_reset_reset_bridge_in_reset.reset
		input  wire [31:0]  dma_0_write_master_address,                          //                            dma_0_write_master.address
		output wire         dma_0_write_master_waitrequest,                      //                                              .waitrequest
		input  wire [15:0]  dma_0_write_master_byteenable,                       //                                              .byteenable
		input  wire         dma_0_write_master_chipselect,                       //                                              .chipselect
		input  wire         dma_0_write_master_write,                            //                                              .write
		input  wire [127:0] dma_0_write_master_writedata,                        //                                              .writedata
		input  wire [31:0]  hps_to_plasma_dma_write_master_address,              //                hps_to_plasma_dma_write_master.address
		output wire         hps_to_plasma_dma_write_master_waitrequest,          //                                              .waitrequest
		input  wire [3:0]   hps_to_plasma_dma_write_master_byteenable,           //                                              .byteenable
		input  wire         hps_to_plasma_dma_write_master_chipselect,           //                                              .chipselect
		input  wire         hps_to_plasma_dma_write_master_write,                //                                              .write
		input  wire [31:0]  hps_to_plasma_dma_write_master_writedata,            //                                              .writedata
		output wire [31:0]  plasma_soc_0_avalon_slave_0_address,                 //                   plasma_soc_0_avalon_slave_0.address
		output wire         plasma_soc_0_avalon_slave_0_write,                   //                                              .write
		output wire         plasma_soc_0_avalon_slave_0_read,                    //                                              .read
		input  wire [31:0]  plasma_soc_0_avalon_slave_0_readdata,                //                                              .readdata
		output wire [31:0]  plasma_soc_0_avalon_slave_0_writedata,               //                                              .writedata
		output wire [3:0]   plasma_soc_0_avalon_slave_0_byteenable,              //                                              .byteenable
		input  wire         plasma_soc_0_avalon_slave_0_waitrequest,             //                                              .waitrequest
		input  wire [1:0]   plasma_soc_0_avalon_slave_0_response                 //                                              .response
	);

	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_waitrequest;                  // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_waitrequest -> hps_to_plasma_dma_write_master_translator:uav_waitrequest
	wire    [2:0] hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_burstcount;                   // hps_to_plasma_dma_write_master_translator:uav_burstcount -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_burstcount
	wire   [31:0] hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_writedata;                    // hps_to_plasma_dma_write_master_translator:uav_writedata -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_writedata
	wire   [31:0] hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_address;                      // hps_to_plasma_dma_write_master_translator:uav_address -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_address
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_lock;                         // hps_to_plasma_dma_write_master_translator:uav_lock -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_lock
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_write;                        // hps_to_plasma_dma_write_master_translator:uav_write -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_write
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_read;                         // hps_to_plasma_dma_write_master_translator:uav_read -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_read
	wire   [31:0] hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_readdata;                     // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_readdata -> hps_to_plasma_dma_write_master_translator:uav_readdata
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_debugaccess;                  // hps_to_plasma_dma_write_master_translator:uav_debugaccess -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_debugaccess
	wire    [3:0] hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_byteenable;                   // hps_to_plasma_dma_write_master_translator:uav_byteenable -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_byteenable
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_readdatavalid;                // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:av_readdatavalid -> hps_to_plasma_dma_write_master_translator:uav_readdatavalid
	wire          rsp_xbar_mux_src_endofpacket;                                                                     // rsp_xbar_mux:src_endofpacket -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:rp_endofpacket
	wire          rsp_xbar_mux_src_valid;                                                                           // rsp_xbar_mux:src_valid -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:rp_valid
	wire          rsp_xbar_mux_src_startofpacket;                                                                   // rsp_xbar_mux:src_startofpacket -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:rp_startofpacket
	wire  [103:0] rsp_xbar_mux_src_data;                                                                            // rsp_xbar_mux:src_data -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:rp_data
	wire    [1:0] rsp_xbar_mux_src_channel;                                                                         // rsp_xbar_mux:src_channel -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:rp_channel
	wire          rsp_xbar_mux_src_ready;                                                                           // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:rp_ready -> rsp_xbar_mux:src_ready
	wire          dma_0_write_master_translator_avalon_universal_master_0_waitrequest;                              // dma_0_write_master_translator_avalon_universal_master_0_agent:av_waitrequest -> dma_0_write_master_translator:uav_waitrequest
	wire    [4:0] dma_0_write_master_translator_avalon_universal_master_0_burstcount;                               // dma_0_write_master_translator:uav_burstcount -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_burstcount
	wire  [127:0] dma_0_write_master_translator_avalon_universal_master_0_writedata;                                // dma_0_write_master_translator:uav_writedata -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_writedata
	wire   [31:0] dma_0_write_master_translator_avalon_universal_master_0_address;                                  // dma_0_write_master_translator:uav_address -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_address
	wire          dma_0_write_master_translator_avalon_universal_master_0_lock;                                     // dma_0_write_master_translator:uav_lock -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_lock
	wire          dma_0_write_master_translator_avalon_universal_master_0_write;                                    // dma_0_write_master_translator:uav_write -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_write
	wire          dma_0_write_master_translator_avalon_universal_master_0_read;                                     // dma_0_write_master_translator:uav_read -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_read
	wire  [127:0] dma_0_write_master_translator_avalon_universal_master_0_readdata;                                 // dma_0_write_master_translator_avalon_universal_master_0_agent:av_readdata -> dma_0_write_master_translator:uav_readdata
	wire          dma_0_write_master_translator_avalon_universal_master_0_debugaccess;                              // dma_0_write_master_translator:uav_debugaccess -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_debugaccess
	wire   [15:0] dma_0_write_master_translator_avalon_universal_master_0_byteenable;                               // dma_0_write_master_translator:uav_byteenable -> dma_0_write_master_translator_avalon_universal_master_0_agent:av_byteenable
	wire          dma_0_write_master_translator_avalon_universal_master_0_readdatavalid;                            // dma_0_write_master_translator_avalon_universal_master_0_agent:av_readdatavalid -> dma_0_write_master_translator:uav_readdatavalid
	wire    [1:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_response;                // plasma_soc_0_avalon_slave_0_translator:uav_response -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_response
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_waitrequest;             // plasma_soc_0_avalon_slave_0_translator:uav_waitrequest -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_waitrequest
	wire    [2:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_burstcount;              // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_burstcount -> plasma_soc_0_avalon_slave_0_translator:uav_burstcount
	wire   [31:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_writedata;               // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_writedata -> plasma_soc_0_avalon_slave_0_translator:uav_writedata
	wire   [31:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_address;                 // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_address -> plasma_soc_0_avalon_slave_0_translator:uav_address
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_write;                   // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_write -> plasma_soc_0_avalon_slave_0_translator:uav_write
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_lock;                    // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_lock -> plasma_soc_0_avalon_slave_0_translator:uav_lock
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_read;                    // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_read -> plasma_soc_0_avalon_slave_0_translator:uav_read
	wire   [31:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_readdata;                // plasma_soc_0_avalon_slave_0_translator:uav_readdata -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_readdata
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_readdatavalid;           // plasma_soc_0_avalon_slave_0_translator:uav_readdatavalid -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_readdatavalid
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_debugaccess;             // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_debugaccess -> plasma_soc_0_avalon_slave_0_translator:uav_debugaccess
	wire    [3:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_byteenable;              // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:m0_byteenable -> plasma_soc_0_avalon_slave_0_translator:uav_byteenable
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_endofpacket;      // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_source_endofpacket -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_endofpacket
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_valid;            // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_source_valid -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_valid
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_startofpacket;    // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_source_startofpacket -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_startofpacket
	wire  [104:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_data;             // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_source_data -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_data
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_ready;            // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:in_ready -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_source_ready
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket;   // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_endofpacket -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_sink_endofpacket
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid;         // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_valid -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_sink_valid
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket; // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_startofpacket -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_sink_startofpacket
	wire  [104:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data;          // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_data -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_sink_data
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready;         // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rf_sink_ready -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo:out_ready
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid;       // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rdata_fifo_src_valid -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_valid
	wire   [33:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data;        // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rdata_fifo_src_data -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_data
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready;       // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_ready -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rdata_fifo_src_ready
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket;         // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:cp_endofpacket -> addr_router:sink_endofpacket
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_valid;               // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:cp_valid -> addr_router:sink_valid
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket;       // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:cp_startofpacket -> addr_router:sink_startofpacket
	wire  [103:0] hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_data;                // hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:cp_data -> addr_router:sink_data
	wire          hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_ready;               // addr_router:sink_ready -> hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent:cp_ready
	wire          addr_router_src_endofpacket;                                                                      // addr_router:src_endofpacket -> cmd_xbar_demux:sink_endofpacket
	wire          addr_router_src_valid;                                                                            // addr_router:src_valid -> cmd_xbar_demux:sink_valid
	wire          addr_router_src_startofpacket;                                                                    // addr_router:src_startofpacket -> cmd_xbar_demux:sink_startofpacket
	wire  [103:0] addr_router_src_data;                                                                             // addr_router:src_data -> cmd_xbar_demux:sink_data
	wire    [1:0] addr_router_src_channel;                                                                          // addr_router:src_channel -> cmd_xbar_demux:sink_channel
	wire          addr_router_src_ready;                                                                            // cmd_xbar_demux:sink_ready -> addr_router:src_ready
	wire          dma_0_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket;                     // dma_0_write_master_translator_avalon_universal_master_0_agent:cp_endofpacket -> addr_router_001:sink_endofpacket
	wire          dma_0_write_master_translator_avalon_universal_master_0_agent_cp_valid;                           // dma_0_write_master_translator_avalon_universal_master_0_agent:cp_valid -> addr_router_001:sink_valid
	wire          dma_0_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket;                   // dma_0_write_master_translator_avalon_universal_master_0_agent:cp_startofpacket -> addr_router_001:sink_startofpacket
	wire  [211:0] dma_0_write_master_translator_avalon_universal_master_0_agent_cp_data;                            // dma_0_write_master_translator_avalon_universal_master_0_agent:cp_data -> addr_router_001:sink_data
	wire          dma_0_write_master_translator_avalon_universal_master_0_agent_cp_ready;                           // addr_router_001:sink_ready -> dma_0_write_master_translator_avalon_universal_master_0_agent:cp_ready
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_endofpacket;             // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rp_endofpacket -> id_router:sink_endofpacket
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_valid;                   // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rp_valid -> id_router:sink_valid
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_startofpacket;           // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rp_startofpacket -> id_router:sink_startofpacket
	wire  [103:0] plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_data;                    // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rp_data -> id_router:sink_data
	wire          plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_ready;                   // id_router:sink_ready -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:rp_ready
	wire          id_router_src_endofpacket;                                                                        // id_router:src_endofpacket -> rsp_xbar_demux:sink_endofpacket
	wire          id_router_src_valid;                                                                              // id_router:src_valid -> rsp_xbar_demux:sink_valid
	wire          id_router_src_startofpacket;                                                                      // id_router:src_startofpacket -> rsp_xbar_demux:sink_startofpacket
	wire  [103:0] id_router_src_data;                                                                               // id_router:src_data -> rsp_xbar_demux:sink_data
	wire    [1:0] id_router_src_channel;                                                                            // id_router:src_channel -> rsp_xbar_demux:sink_channel
	wire          id_router_src_ready;                                                                              // rsp_xbar_demux:sink_ready -> id_router:src_ready
	wire          cmd_xbar_mux_src_endofpacket;                                                                     // cmd_xbar_mux:src_endofpacket -> burst_adapter:sink0_endofpacket
	wire          cmd_xbar_mux_src_valid;                                                                           // cmd_xbar_mux:src_valid -> burst_adapter:sink0_valid
	wire          cmd_xbar_mux_src_startofpacket;                                                                   // cmd_xbar_mux:src_startofpacket -> burst_adapter:sink0_startofpacket
	wire  [103:0] cmd_xbar_mux_src_data;                                                                            // cmd_xbar_mux:src_data -> burst_adapter:sink0_data
	wire    [1:0] cmd_xbar_mux_src_channel;                                                                         // cmd_xbar_mux:src_channel -> burst_adapter:sink0_channel
	wire          cmd_xbar_mux_src_ready;                                                                           // burst_adapter:sink0_ready -> cmd_xbar_mux:src_ready
	wire          burst_adapter_source0_endofpacket;                                                                // burst_adapter:source0_endofpacket -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:cp_endofpacket
	wire          burst_adapter_source0_valid;                                                                      // burst_adapter:source0_valid -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:cp_valid
	wire          burst_adapter_source0_startofpacket;                                                              // burst_adapter:source0_startofpacket -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:cp_startofpacket
	wire  [103:0] burst_adapter_source0_data;                                                                       // burst_adapter:source0_data -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:cp_data
	wire          burst_adapter_source0_ready;                                                                      // plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:cp_ready -> burst_adapter:source0_ready
	wire    [1:0] burst_adapter_source0_channel;                                                                    // burst_adapter:source0_channel -> plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent:cp_channel
	wire          cmd_xbar_demux_src0_endofpacket;                                                                  // cmd_xbar_demux:src0_endofpacket -> cmd_xbar_mux:sink0_endofpacket
	wire          cmd_xbar_demux_src0_valid;                                                                        // cmd_xbar_demux:src0_valid -> cmd_xbar_mux:sink0_valid
	wire          cmd_xbar_demux_src0_startofpacket;                                                                // cmd_xbar_demux:src0_startofpacket -> cmd_xbar_mux:sink0_startofpacket
	wire  [103:0] cmd_xbar_demux_src0_data;                                                                         // cmd_xbar_demux:src0_data -> cmd_xbar_mux:sink0_data
	wire    [1:0] cmd_xbar_demux_src0_channel;                                                                      // cmd_xbar_demux:src0_channel -> cmd_xbar_mux:sink0_channel
	wire          cmd_xbar_demux_src0_ready;                                                                        // cmd_xbar_mux:sink0_ready -> cmd_xbar_demux:src0_ready
	wire          cmd_xbar_demux_001_src0_endofpacket;                                                              // cmd_xbar_demux_001:src0_endofpacket -> cmd_xbar_mux:sink1_endofpacket
	wire          cmd_xbar_demux_001_src0_valid;                                                                    // cmd_xbar_demux_001:src0_valid -> cmd_xbar_mux:sink1_valid
	wire          cmd_xbar_demux_001_src0_startofpacket;                                                            // cmd_xbar_demux_001:src0_startofpacket -> cmd_xbar_mux:sink1_startofpacket
	wire  [103:0] cmd_xbar_demux_001_src0_data;                                                                     // cmd_xbar_demux_001:src0_data -> cmd_xbar_mux:sink1_data
	wire    [1:0] cmd_xbar_demux_001_src0_channel;                                                                  // cmd_xbar_demux_001:src0_channel -> cmd_xbar_mux:sink1_channel
	wire          cmd_xbar_demux_001_src0_ready;                                                                    // cmd_xbar_mux:sink1_ready -> cmd_xbar_demux_001:src0_ready
	wire          rsp_xbar_demux_src0_endofpacket;                                                                  // rsp_xbar_demux:src0_endofpacket -> rsp_xbar_mux:sink0_endofpacket
	wire          rsp_xbar_demux_src0_valid;                                                                        // rsp_xbar_demux:src0_valid -> rsp_xbar_mux:sink0_valid
	wire          rsp_xbar_demux_src0_startofpacket;                                                                // rsp_xbar_demux:src0_startofpacket -> rsp_xbar_mux:sink0_startofpacket
	wire  [103:0] rsp_xbar_demux_src0_data;                                                                         // rsp_xbar_demux:src0_data -> rsp_xbar_mux:sink0_data
	wire    [1:0] rsp_xbar_demux_src0_channel;                                                                      // rsp_xbar_demux:src0_channel -> rsp_xbar_mux:sink0_channel
	wire          rsp_xbar_demux_src0_ready;                                                                        // rsp_xbar_mux:sink0_ready -> rsp_xbar_demux:src0_ready
	wire          rsp_xbar_demux_src1_endofpacket;                                                                  // rsp_xbar_demux:src1_endofpacket -> rsp_xbar_mux_001:sink0_endofpacket
	wire          rsp_xbar_demux_src1_valid;                                                                        // rsp_xbar_demux:src1_valid -> rsp_xbar_mux_001:sink0_valid
	wire          rsp_xbar_demux_src1_startofpacket;                                                                // rsp_xbar_demux:src1_startofpacket -> rsp_xbar_mux_001:sink0_startofpacket
	wire  [103:0] rsp_xbar_demux_src1_data;                                                                         // rsp_xbar_demux:src1_data -> rsp_xbar_mux_001:sink0_data
	wire    [1:0] rsp_xbar_demux_src1_channel;                                                                      // rsp_xbar_demux:src1_channel -> rsp_xbar_mux_001:sink0_channel
	wire          rsp_xbar_demux_src1_ready;                                                                        // rsp_xbar_mux_001:sink0_ready -> rsp_xbar_demux:src1_ready
	wire          rsp_xbar_mux_001_src_endofpacket;                                                                 // rsp_xbar_mux_001:src_endofpacket -> width_adapter:in_endofpacket
	wire          rsp_xbar_mux_001_src_valid;                                                                       // rsp_xbar_mux_001:src_valid -> width_adapter:in_valid
	wire          rsp_xbar_mux_001_src_startofpacket;                                                               // rsp_xbar_mux_001:src_startofpacket -> width_adapter:in_startofpacket
	wire  [103:0] rsp_xbar_mux_001_src_data;                                                                        // rsp_xbar_mux_001:src_data -> width_adapter:in_data
	wire    [1:0] rsp_xbar_mux_001_src_channel;                                                                     // rsp_xbar_mux_001:src_channel -> width_adapter:in_channel
	wire          rsp_xbar_mux_001_src_ready;                                                                       // width_adapter:in_ready -> rsp_xbar_mux_001:src_ready
	wire          width_adapter_src_endofpacket;                                                                    // width_adapter:out_endofpacket -> dma_0_write_master_translator_avalon_universal_master_0_agent:rp_endofpacket
	wire          width_adapter_src_valid;                                                                          // width_adapter:out_valid -> dma_0_write_master_translator_avalon_universal_master_0_agent:rp_valid
	wire          width_adapter_src_startofpacket;                                                                  // width_adapter:out_startofpacket -> dma_0_write_master_translator_avalon_universal_master_0_agent:rp_startofpacket
	wire  [211:0] width_adapter_src_data;                                                                           // width_adapter:out_data -> dma_0_write_master_translator_avalon_universal_master_0_agent:rp_data
	wire          width_adapter_src_ready;                                                                          // dma_0_write_master_translator_avalon_universal_master_0_agent:rp_ready -> width_adapter:out_ready
	wire    [1:0] width_adapter_src_channel;                                                                        // width_adapter:out_channel -> dma_0_write_master_translator_avalon_universal_master_0_agent:rp_channel
	wire          addr_router_001_src_endofpacket;                                                                  // addr_router_001:src_endofpacket -> width_adapter_001:in_endofpacket
	wire          addr_router_001_src_valid;                                                                        // addr_router_001:src_valid -> width_adapter_001:in_valid
	wire          addr_router_001_src_startofpacket;                                                                // addr_router_001:src_startofpacket -> width_adapter_001:in_startofpacket
	wire  [211:0] addr_router_001_src_data;                                                                         // addr_router_001:src_data -> width_adapter_001:in_data
	wire    [1:0] addr_router_001_src_channel;                                                                      // addr_router_001:src_channel -> width_adapter_001:in_channel
	wire          addr_router_001_src_ready;                                                                        // width_adapter_001:in_ready -> addr_router_001:src_ready
	wire          width_adapter_001_src_endofpacket;                                                                // width_adapter_001:out_endofpacket -> cmd_xbar_demux_001:sink_endofpacket
	wire          width_adapter_001_src_valid;                                                                      // width_adapter_001:out_valid -> cmd_xbar_demux_001:sink_valid
	wire          width_adapter_001_src_startofpacket;                                                              // width_adapter_001:out_startofpacket -> cmd_xbar_demux_001:sink_startofpacket
	wire  [103:0] width_adapter_001_src_data;                                                                       // width_adapter_001:out_data -> cmd_xbar_demux_001:sink_data
	wire          width_adapter_001_src_ready;                                                                      // cmd_xbar_demux_001:sink_ready -> width_adapter_001:out_ready
	wire    [1:0] width_adapter_001_src_channel;                                                                    // width_adapter_001:out_channel -> cmd_xbar_demux_001:sink_channel

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) hps_to_plasma_dma_write_master_translator (
		.clk                      (pll_0_outclk0_clk),                                                                 //                       clk.clk
		.reset                    (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                               //                     reset.reset
		.uav_address              (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount           (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read                 (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write                (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest          (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid        (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable           (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata             (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata            (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock                 (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess          (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address               (hps_to_plasma_dma_write_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest           (hps_to_plasma_dma_write_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable            (hps_to_plasma_dma_write_master_byteenable),                                         //                          .byteenable
		.av_chipselect            (hps_to_plasma_dma_write_master_chipselect),                                         //                          .chipselect
		.av_write                 (hps_to_plasma_dma_write_master_write),                                              //                          .write
		.av_writedata             (hps_to_plasma_dma_write_master_writedata),                                          //                          .writedata
		.av_burstcount            (1'b1),                                                                              //               (terminated)
		.av_beginbursttransfer    (1'b0),                                                                              //               (terminated)
		.av_begintransfer         (1'b0),                                                                              //               (terminated)
		.av_read                  (1'b0),                                                                              //               (terminated)
		.av_readdata              (),                                                                                  //               (terminated)
		.av_readdatavalid         (),                                                                                  //               (terminated)
		.av_lock                  (1'b0),                                                                              //               (terminated)
		.av_debugaccess           (1'b0),                                                                              //               (terminated)
		.uav_clken                (),                                                                                  //               (terminated)
		.av_clken                 (1'b1),                                                                              //               (terminated)
		.uav_response             (2'b00),                                                                             //               (terminated)
		.av_response              (),                                                                                  //               (terminated)
		.uav_writeresponserequest (),                                                                                  //               (terminated)
		.uav_writeresponsevalid   (1'b0),                                                                              //               (terminated)
		.av_writeresponserequest  (1'b0),                                                                              //               (terminated)
		.av_writeresponsevalid    ()                                                                                   //               (terminated)
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (128),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (16),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (5),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (16),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dma_0_write_master_translator (
		.clk                      (pll_0_outclk0_clk),                                                     //                       clk.clk
		.reset                    (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                   //                     reset.reset
		.uav_address              (dma_0_write_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount           (dma_0_write_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read                 (dma_0_write_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write                (dma_0_write_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest          (dma_0_write_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid        (dma_0_write_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable           (dma_0_write_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata             (dma_0_write_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata            (dma_0_write_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock                 (dma_0_write_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess          (dma_0_write_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address               (dma_0_write_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest           (dma_0_write_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable            (dma_0_write_master_byteenable),                                         //                          .byteenable
		.av_chipselect            (dma_0_write_master_chipselect),                                         //                          .chipselect
		.av_write                 (dma_0_write_master_write),                                              //                          .write
		.av_writedata             (dma_0_write_master_writedata),                                          //                          .writedata
		.av_burstcount            (1'b1),                                                                  //               (terminated)
		.av_beginbursttransfer    (1'b0),                                                                  //               (terminated)
		.av_begintransfer         (1'b0),                                                                  //               (terminated)
		.av_read                  (1'b0),                                                                  //               (terminated)
		.av_readdata              (),                                                                      //               (terminated)
		.av_readdatavalid         (),                                                                      //               (terminated)
		.av_lock                  (1'b0),                                                                  //               (terminated)
		.av_debugaccess           (1'b0),                                                                  //               (terminated)
		.uav_clken                (),                                                                      //               (terminated)
		.av_clken                 (1'b1),                                                                  //               (terminated)
		.uav_response             (2'b00),                                                                 //               (terminated)
		.av_response              (),                                                                      //               (terminated)
		.uav_writeresponserequest (),                                                                      //               (terminated)
		.uav_writeresponsevalid   (1'b0),                                                                  //               (terminated)
		.av_writeresponserequest  (1'b0),                                                                  //               (terminated)
		.av_writeresponsevalid    ()                                                                       //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (32),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (1),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) plasma_soc_0_avalon_slave_0_translator (
		.clk                      (pll_0_outclk0_clk),                                                                      //                      clk.clk
		.reset                    (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                                    //                    reset.reset
		.uav_address              (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_burstcount),    //                         .burstcount
		.uav_read                 (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_read),          //                         .read
		.uav_write                (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_write),         //                         .write
		.uav_waitrequest          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid        (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata             (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_readdata),      //                         .readdata
		.uav_writedata            (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_writedata),     //                         .writedata
		.uav_lock                 (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_lock),          //                         .lock
		.uav_debugaccess          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_debugaccess),   //                         .debugaccess
		.uav_response             (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_response),      //                         .response
		.av_address               (plasma_soc_0_avalon_slave_0_address),                                                    //      avalon_anti_slave_0.address
		.av_write                 (plasma_soc_0_avalon_slave_0_write),                                                      //                         .write
		.av_read                  (plasma_soc_0_avalon_slave_0_read),                                                       //                         .read
		.av_readdata              (plasma_soc_0_avalon_slave_0_readdata),                                                   //                         .readdata
		.av_writedata             (plasma_soc_0_avalon_slave_0_writedata),                                                  //                         .writedata
		.av_byteenable            (plasma_soc_0_avalon_slave_0_byteenable),                                                 //                         .byteenable
		.av_waitrequest           (plasma_soc_0_avalon_slave_0_waitrequest),                                                //                         .waitrequest
		.av_response              (plasma_soc_0_avalon_slave_0_response),                                                   //                         .response
		.av_begintransfer         (),                                                                                       //              (terminated)
		.av_beginbursttransfer    (),                                                                                       //              (terminated)
		.av_burstcount            (),                                                                                       //              (terminated)
		.av_readdatavalid         (1'b0),                                                                                   //              (terminated)
		.av_writebyteenable       (),                                                                                       //              (terminated)
		.av_lock                  (),                                                                                       //              (terminated)
		.av_chipselect            (),                                                                                       //              (terminated)
		.av_clken                 (),                                                                                       //              (terminated)
		.uav_clken                (1'b0),                                                                                   //              (terminated)
		.av_debugaccess           (),                                                                                       //              (terminated)
		.av_outputenable          (),                                                                                       //              (terminated)
		.uav_writeresponserequest (1'b0),                                                                                   //              (terminated)
		.uav_writeresponsevalid   (),                                                                                       //              (terminated)
		.av_writeresponserequest  (),                                                                                       //              (terminated)
		.av_writeresponsevalid    (1'b0)                                                                                    //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_PROTECTION_H          (94),
		.PKT_PROTECTION_L          (92),
		.PKT_BEGIN_BURST           (87),
		.PKT_BURSTWRAP_H           (79),
		.PKT_BURSTWRAP_L           (79),
		.PKT_BURST_SIZE_H          (82),
		.PKT_BURST_SIZE_L          (80),
		.PKT_BURST_TYPE_H          (84),
		.PKT_BURST_TYPE_L          (83),
		.PKT_BYTE_CNT_H            (78),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_TRANS_LOCK            (72),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (89),
		.PKT_SRC_ID_L              (89),
		.PKT_DEST_ID_H             (90),
		.PKT_DEST_ID_L             (90),
		.PKT_THREAD_ID_H           (91),
		.PKT_THREAD_ID_L           (91),
		.PKT_CACHE_H               (98),
		.PKT_CACHE_L               (95),
		.PKT_DATA_SIDEBAND_H       (86),
		.PKT_DATA_SIDEBAND_L       (86),
		.PKT_QOS_H                 (88),
		.PKT_QOS_L                 (88),
		.PKT_ADDR_SIDEBAND_H       (85),
		.PKT_ADDR_SIDEBAND_L       (85),
		.PKT_RESPONSE_STATUS_H     (100),
		.PKT_RESPONSE_STATUS_L     (99),
		.PKT_ORI_BURST_SIZE_L      (101),
		.PKT_ORI_BURST_SIZE_H      (103),
		.ST_DATA_W                 (104),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (1),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent (
		.clk                     (pll_0_outclk0_clk),                                                                          //       clk.clk
		.reset                   (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                                        // clk_reset.reset
		.av_address              (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_address),                //        av.address
		.av_write                (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_write),                  //          .write
		.av_read                 (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_read),                   //          .read
		.av_writedata            (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_writedata),              //          .writedata
		.av_readdata             (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_readdata),               //          .readdata
		.av_waitrequest          (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_waitrequest),            //          .waitrequest
		.av_readdatavalid        (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_readdatavalid),          //          .readdatavalid
		.av_byteenable           (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_byteenable),             //          .byteenable
		.av_burstcount           (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_burstcount),             //          .burstcount
		.av_debugaccess          (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_debugaccess),            //          .debugaccess
		.av_lock                 (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_lock),                   //          .lock
		.cp_valid                (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_valid),         //        cp.valid
		.cp_data                 (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.cp_startofpacket        (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.cp_endofpacket          (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.cp_ready                (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_ready),         //          .ready
		.rp_valid                (rsp_xbar_mux_src_valid),                                                                     //        rp.valid
		.rp_data                 (rsp_xbar_mux_src_data),                                                                      //          .data
		.rp_channel              (rsp_xbar_mux_src_channel),                                                                   //          .channel
		.rp_startofpacket        (rsp_xbar_mux_src_startofpacket),                                                             //          .startofpacket
		.rp_endofpacket          (rsp_xbar_mux_src_endofpacket),                                                               //          .endofpacket
		.rp_ready                (rsp_xbar_mux_src_ready),                                                                     //          .ready
		.av_response             (),                                                                                           // (terminated)
		.av_writeresponserequest (1'b0),                                                                                       // (terminated)
		.av_writeresponsevalid   ()                                                                                            // (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_PROTECTION_H          (202),
		.PKT_PROTECTION_L          (200),
		.PKT_BEGIN_BURST           (195),
		.PKT_BURSTWRAP_H           (187),
		.PKT_BURSTWRAP_L           (187),
		.PKT_BURST_SIZE_H          (190),
		.PKT_BURST_SIZE_L          (188),
		.PKT_BURST_TYPE_H          (192),
		.PKT_BURST_TYPE_L          (191),
		.PKT_BYTE_CNT_H            (186),
		.PKT_BYTE_CNT_L            (182),
		.PKT_ADDR_H                (175),
		.PKT_ADDR_L                (144),
		.PKT_TRANS_COMPRESSED_READ (176),
		.PKT_TRANS_POSTED          (177),
		.PKT_TRANS_WRITE           (178),
		.PKT_TRANS_READ            (179),
		.PKT_TRANS_LOCK            (180),
		.PKT_TRANS_EXCLUSIVE       (181),
		.PKT_DATA_H                (127),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (143),
		.PKT_BYTEEN_L              (128),
		.PKT_SRC_ID_H              (197),
		.PKT_SRC_ID_L              (197),
		.PKT_DEST_ID_H             (198),
		.PKT_DEST_ID_L             (198),
		.PKT_THREAD_ID_H           (199),
		.PKT_THREAD_ID_L           (199),
		.PKT_CACHE_H               (206),
		.PKT_CACHE_L               (203),
		.PKT_DATA_SIDEBAND_H       (194),
		.PKT_DATA_SIDEBAND_L       (194),
		.PKT_QOS_H                 (196),
		.PKT_QOS_L                 (196),
		.PKT_ADDR_SIDEBAND_H       (193),
		.PKT_ADDR_SIDEBAND_L       (193),
		.PKT_RESPONSE_STATUS_H     (208),
		.PKT_RESPONSE_STATUS_L     (207),
		.PKT_ORI_BURST_SIZE_L      (209),
		.PKT_ORI_BURST_SIZE_H      (211),
		.ST_DATA_W                 (212),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (5),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) dma_0_write_master_translator_avalon_universal_master_0_agent (
		.clk                     (pll_0_outclk0_clk),                                                              //       clk.clk
		.reset                   (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                            // clk_reset.reset
		.av_address              (dma_0_write_master_translator_avalon_universal_master_0_address),                //        av.address
		.av_write                (dma_0_write_master_translator_avalon_universal_master_0_write),                  //          .write
		.av_read                 (dma_0_write_master_translator_avalon_universal_master_0_read),                   //          .read
		.av_writedata            (dma_0_write_master_translator_avalon_universal_master_0_writedata),              //          .writedata
		.av_readdata             (dma_0_write_master_translator_avalon_universal_master_0_readdata),               //          .readdata
		.av_waitrequest          (dma_0_write_master_translator_avalon_universal_master_0_waitrequest),            //          .waitrequest
		.av_readdatavalid        (dma_0_write_master_translator_avalon_universal_master_0_readdatavalid),          //          .readdatavalid
		.av_byteenable           (dma_0_write_master_translator_avalon_universal_master_0_byteenable),             //          .byteenable
		.av_burstcount           (dma_0_write_master_translator_avalon_universal_master_0_burstcount),             //          .burstcount
		.av_debugaccess          (dma_0_write_master_translator_avalon_universal_master_0_debugaccess),            //          .debugaccess
		.av_lock                 (dma_0_write_master_translator_avalon_universal_master_0_lock),                   //          .lock
		.cp_valid                (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_valid),         //        cp.valid
		.cp_data                 (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.cp_startofpacket        (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.cp_endofpacket          (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.cp_ready                (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_ready),         //          .ready
		.rp_valid                (width_adapter_src_valid),                                                        //        rp.valid
		.rp_data                 (width_adapter_src_data),                                                         //          .data
		.rp_channel              (width_adapter_src_channel),                                                      //          .channel
		.rp_startofpacket        (width_adapter_src_startofpacket),                                                //          .startofpacket
		.rp_endofpacket          (width_adapter_src_endofpacket),                                                  //          .endofpacket
		.rp_ready                (width_adapter_src_ready),                                                        //          .ready
		.av_response             (),                                                                               // (terminated)
		.av_writeresponserequest (1'b0),                                                                           // (terminated)
		.av_writeresponsevalid   ()                                                                                // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BEGIN_BURST           (87),
		.PKT_SYMBOL_W              (8),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_TRANS_LOCK            (72),
		.PKT_SRC_ID_H              (89),
		.PKT_SRC_ID_L              (89),
		.PKT_DEST_ID_H             (90),
		.PKT_DEST_ID_L             (90),
		.PKT_BURSTWRAP_H           (79),
		.PKT_BURSTWRAP_L           (79),
		.PKT_BYTE_CNT_H            (78),
		.PKT_BYTE_CNT_L            (74),
		.PKT_PROTECTION_H          (94),
		.PKT_PROTECTION_L          (92),
		.PKT_RESPONSE_STATUS_H     (100),
		.PKT_RESPONSE_STATUS_L     (99),
		.PKT_BURST_SIZE_H          (82),
		.PKT_BURST_SIZE_L          (80),
		.PKT_ORI_BURST_SIZE_L      (101),
		.PKT_ORI_BURST_SIZE_H      (103),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (104),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (0)
	) plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent (
		.clk                     (pll_0_outclk0_clk),                                                                                //             clk.clk
		.reset                   (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                                              //       clk_reset.reset
		.m0_address              (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_lock),                    //                .lock
		.m0_readdata             (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_read),                    //                .read
		.m0_waitrequest          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_writedata),               //                .writedata
		.m0_write                (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_write),                   //                .write
		.m0_response             (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_m0_response),                //                .response
		.rp_endofpacket          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_ready),                   //                .ready
		.rp_valid                (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_valid),                   //                .valid
		.rp_data                 (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_data),                    //                .data
		.rp_startofpacket        (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (burst_adapter_source0_ready),                                                                      //              cp.ready
		.cp_valid                (burst_adapter_source0_valid),                                                                      //                .valid
		.cp_data                 (burst_adapter_source0_data),                                                                       //                .data
		.cp_startofpacket        (burst_adapter_source0_startofpacket),                                                              //                .startofpacket
		.cp_endofpacket          (burst_adapter_source0_endofpacket),                                                                //                .endofpacket
		.cp_channel              (burst_adapter_source0_channel),                                                                    //                .channel
		.rf_sink_ready           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_sink_data    (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.rdata_fifo_src_ready    (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.m0_writeresponserequest (),                                                                                                 //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                                              //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (105),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo (
		.clk               (pll_0_outclk0_clk),                                                                                //       clk.clk
		.reset             (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                                              // clk_reset.reset
		.in_data           (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_data),             //        in.data
		.in_valid          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_valid),            //          .valid
		.in_ready          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                                                            // (terminated)
		.csr_read          (1'b0),                                                                                             // (terminated)
		.csr_write         (1'b0),                                                                                             // (terminated)
		.csr_readdata      (),                                                                                                 // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                                             // (terminated)
		.almost_full_data  (),                                                                                                 // (terminated)
		.almost_empty_data (),                                                                                                 // (terminated)
		.in_empty          (1'b0),                                                                                             // (terminated)
		.out_empty         (),                                                                                                 // (terminated)
		.in_error          (1'b0),                                                                                             // (terminated)
		.out_error         (),                                                                                                 // (terminated)
		.in_channel        (1'b0),                                                                                             // (terminated)
		.out_channel       ()                                                                                                  // (terminated)
	);

	de1_soc_mm_interconnect_3_addr_router addr_router (
		.sink_ready         (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_ready),         //      sink.ready
		.sink_valid         (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_valid),         //          .valid
		.sink_data          (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.sink_startofpacket (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (hps_to_plasma_dma_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.clk                (pll_0_outclk0_clk),                                                                          //       clk.clk
		.reset              (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                                        // clk_reset.reset
		.src_ready          (addr_router_src_ready),                                                                      //       src.ready
		.src_valid          (addr_router_src_valid),                                                                      //          .valid
		.src_data           (addr_router_src_data),                                                                       //          .data
		.src_channel        (addr_router_src_channel),                                                                    //          .channel
		.src_startofpacket  (addr_router_src_startofpacket),                                                              //          .startofpacket
		.src_endofpacket    (addr_router_src_endofpacket)                                                                 //          .endofpacket
	);

	de1_soc_mm_interconnect_3_addr_router_001 addr_router_001 (
		.sink_ready         (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_ready),         //      sink.ready
		.sink_valid         (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_valid),         //          .valid
		.sink_data          (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.sink_startofpacket (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (dma_0_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.clk                (pll_0_outclk0_clk),                                                              //       clk.clk
		.reset              (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                            // clk_reset.reset
		.src_ready          (addr_router_001_src_ready),                                                      //       src.ready
		.src_valid          (addr_router_001_src_valid),                                                      //          .valid
		.src_data           (addr_router_001_src_data),                                                       //          .data
		.src_channel        (addr_router_001_src_channel),                                                    //          .channel
		.src_startofpacket  (addr_router_001_src_startofpacket),                                              //          .startofpacket
		.src_endofpacket    (addr_router_001_src_endofpacket)                                                 //          .endofpacket
	);

	de1_soc_mm_interconnect_3_id_router id_router (
		.sink_ready         (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_ready),         //      sink.ready
		.sink_valid         (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_valid),         //          .valid
		.sink_data          (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_data),          //          .data
		.sink_startofpacket (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (plasma_soc_0_avalon_slave_0_translator_avalon_universal_slave_0_agent_rp_endofpacket),   //          .endofpacket
		.clk                (pll_0_outclk0_clk),                                                                      //       clk.clk
		.reset              (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset),                                    // clk_reset.reset
		.src_ready          (id_router_src_ready),                                                                    //       src.ready
		.src_valid          (id_router_src_valid),                                                                    //          .valid
		.src_data           (id_router_src_data),                                                                     //          .data
		.src_channel        (id_router_src_channel),                                                                  //          .channel
		.src_startofpacket  (id_router_src_startofpacket),                                                            //          .startofpacket
		.src_endofpacket    (id_router_src_endofpacket)                                                               //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_BEGIN_BURST           (87),
		.PKT_BYTE_CNT_H            (78),
		.PKT_BYTE_CNT_L            (74),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_BURST_SIZE_H          (82),
		.PKT_BURST_SIZE_L          (80),
		.PKT_BURST_TYPE_H          (84),
		.PKT_BURST_TYPE_L          (83),
		.PKT_BURSTWRAP_H           (79),
		.PKT_BURSTWRAP_L           (79),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (104),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (76),
		.OUT_BURSTWRAP_H           (79),
		.COMPRESSED_READ_SUPPORT   (0),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1)
	) burst_adapter (
		.clk                   (pll_0_outclk0_clk),                                   //       cr0.clk
		.reset                 (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (cmd_xbar_mux_src_valid),                              //     sink0.valid
		.sink0_data            (cmd_xbar_mux_src_data),                               //          .data
		.sink0_channel         (cmd_xbar_mux_src_channel),                            //          .channel
		.sink0_startofpacket   (cmd_xbar_mux_src_startofpacket),                      //          .startofpacket
		.sink0_endofpacket     (cmd_xbar_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready           (cmd_xbar_mux_src_ready),                              //          .ready
		.source0_valid         (burst_adapter_source0_valid),                         //   source0.valid
		.source0_data          (burst_adapter_source0_data),                          //          .data
		.source0_channel       (burst_adapter_source0_channel),                       //          .channel
		.source0_startofpacket (burst_adapter_source0_startofpacket),                 //          .startofpacket
		.source0_endofpacket   (burst_adapter_source0_endofpacket),                   //          .endofpacket
		.source0_ready         (burst_adapter_source0_ready)                          //          .ready
	);

	de1_soc_mm_interconnect_3_cmd_xbar_demux cmd_xbar_demux (
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (addr_router_src_ready),                               //      sink.ready
		.sink_channel       (addr_router_src_channel),                             //          .channel
		.sink_data          (addr_router_src_data),                                //          .data
		.sink_startofpacket (addr_router_src_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (addr_router_src_endofpacket),                         //          .endofpacket
		.sink_valid         (addr_router_src_valid),                               //          .valid
		.src0_ready         (cmd_xbar_demux_src0_ready),                           //      src0.ready
		.src0_valid         (cmd_xbar_demux_src0_valid),                           //          .valid
		.src0_data          (cmd_xbar_demux_src0_data),                            //          .data
		.src0_channel       (cmd_xbar_demux_src0_channel),                         //          .channel
		.src0_startofpacket (cmd_xbar_demux_src0_startofpacket),                   //          .startofpacket
		.src0_endofpacket   (cmd_xbar_demux_src0_endofpacket)                      //          .endofpacket
	);

	de1_soc_mm_interconnect_3_cmd_xbar_demux cmd_xbar_demux_001 (
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (width_adapter_001_src_ready),                         //      sink.ready
		.sink_channel       (width_adapter_001_src_channel),                       //          .channel
		.sink_data          (width_adapter_001_src_data),                          //          .data
		.sink_startofpacket (width_adapter_001_src_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (width_adapter_001_src_endofpacket),                   //          .endofpacket
		.sink_valid         (width_adapter_001_src_valid),                         //          .valid
		.src0_ready         (cmd_xbar_demux_001_src0_ready),                       //      src0.ready
		.src0_valid         (cmd_xbar_demux_001_src0_valid),                       //          .valid
		.src0_data          (cmd_xbar_demux_001_src0_data),                        //          .data
		.src0_channel       (cmd_xbar_demux_001_src0_channel),                     //          .channel
		.src0_startofpacket (cmd_xbar_demux_001_src0_startofpacket),               //          .startofpacket
		.src0_endofpacket   (cmd_xbar_demux_001_src0_endofpacket)                  //          .endofpacket
	);

	de1_soc_mm_interconnect_3_cmd_xbar_mux cmd_xbar_mux (
		.clk                 (pll_0_outclk0_clk),                                   //       clk.clk
		.reset               (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_xbar_mux_src_ready),                              //       src.ready
		.src_valid           (cmd_xbar_mux_src_valid),                              //          .valid
		.src_data            (cmd_xbar_mux_src_data),                               //          .data
		.src_channel         (cmd_xbar_mux_src_channel),                            //          .channel
		.src_startofpacket   (cmd_xbar_mux_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (cmd_xbar_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (cmd_xbar_demux_src0_ready),                           //     sink0.ready
		.sink0_valid         (cmd_xbar_demux_src0_valid),                           //          .valid
		.sink0_channel       (cmd_xbar_demux_src0_channel),                         //          .channel
		.sink0_data          (cmd_xbar_demux_src0_data),                            //          .data
		.sink0_startofpacket (cmd_xbar_demux_src0_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (cmd_xbar_demux_src0_endofpacket),                     //          .endofpacket
		.sink1_ready         (cmd_xbar_demux_001_src0_ready),                       //     sink1.ready
		.sink1_valid         (cmd_xbar_demux_001_src0_valid),                       //          .valid
		.sink1_channel       (cmd_xbar_demux_001_src0_channel),                     //          .channel
		.sink1_data          (cmd_xbar_demux_001_src0_data),                        //          .data
		.sink1_startofpacket (cmd_xbar_demux_001_src0_startofpacket),               //          .startofpacket
		.sink1_endofpacket   (cmd_xbar_demux_001_src0_endofpacket)                  //          .endofpacket
	);

	de1_soc_mm_interconnect_3_rsp_xbar_demux rsp_xbar_demux (
		.clk                (pll_0_outclk0_clk),                                   //       clk.clk
		.reset              (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (id_router_src_ready),                                 //      sink.ready
		.sink_channel       (id_router_src_channel),                               //          .channel
		.sink_data          (id_router_src_data),                                  //          .data
		.sink_startofpacket (id_router_src_startofpacket),                         //          .startofpacket
		.sink_endofpacket   (id_router_src_endofpacket),                           //          .endofpacket
		.sink_valid         (id_router_src_valid),                                 //          .valid
		.src0_ready         (rsp_xbar_demux_src0_ready),                           //      src0.ready
		.src0_valid         (rsp_xbar_demux_src0_valid),                           //          .valid
		.src0_data          (rsp_xbar_demux_src0_data),                            //          .data
		.src0_channel       (rsp_xbar_demux_src0_channel),                         //          .channel
		.src0_startofpacket (rsp_xbar_demux_src0_startofpacket),                   //          .startofpacket
		.src0_endofpacket   (rsp_xbar_demux_src0_endofpacket),                     //          .endofpacket
		.src1_ready         (rsp_xbar_demux_src1_ready),                           //      src1.ready
		.src1_valid         (rsp_xbar_demux_src1_valid),                           //          .valid
		.src1_data          (rsp_xbar_demux_src1_data),                            //          .data
		.src1_channel       (rsp_xbar_demux_src1_channel),                         //          .channel
		.src1_startofpacket (rsp_xbar_demux_src1_startofpacket),                   //          .startofpacket
		.src1_endofpacket   (rsp_xbar_demux_src1_endofpacket)                      //          .endofpacket
	);

	de1_soc_mm_interconnect_3_rsp_xbar_mux rsp_xbar_mux (
		.clk                 (pll_0_outclk0_clk),                                   //       clk.clk
		.reset               (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_xbar_mux_src_ready),                              //       src.ready
		.src_valid           (rsp_xbar_mux_src_valid),                              //          .valid
		.src_data            (rsp_xbar_mux_src_data),                               //          .data
		.src_channel         (rsp_xbar_mux_src_channel),                            //          .channel
		.src_startofpacket   (rsp_xbar_mux_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (rsp_xbar_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (rsp_xbar_demux_src0_ready),                           //     sink0.ready
		.sink0_valid         (rsp_xbar_demux_src0_valid),                           //          .valid
		.sink0_channel       (rsp_xbar_demux_src0_channel),                         //          .channel
		.sink0_data          (rsp_xbar_demux_src0_data),                            //          .data
		.sink0_startofpacket (rsp_xbar_demux_src0_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (rsp_xbar_demux_src0_endofpacket)                      //          .endofpacket
	);

	de1_soc_mm_interconnect_3_rsp_xbar_mux rsp_xbar_mux_001 (
		.clk                 (pll_0_outclk0_clk),                                   //       clk.clk
		.reset               (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_xbar_mux_001_src_ready),                          //       src.ready
		.src_valid           (rsp_xbar_mux_001_src_valid),                          //          .valid
		.src_data            (rsp_xbar_mux_001_src_data),                           //          .data
		.src_channel         (rsp_xbar_mux_001_src_channel),                        //          .channel
		.src_startofpacket   (rsp_xbar_mux_001_src_startofpacket),                  //          .startofpacket
		.src_endofpacket     (rsp_xbar_mux_001_src_endofpacket),                    //          .endofpacket
		.sink0_ready         (rsp_xbar_demux_src1_ready),                           //     sink0.ready
		.sink0_valid         (rsp_xbar_demux_src1_valid),                           //          .valid
		.sink0_channel       (rsp_xbar_demux_src1_channel),                         //          .channel
		.sink0_data          (rsp_xbar_demux_src1_data),                            //          .data
		.sink0_startofpacket (rsp_xbar_demux_src1_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (rsp_xbar_demux_src1_endofpacket)                      //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (67),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (78),
		.IN_PKT_BYTE_CNT_L             (74),
		.IN_PKT_TRANS_COMPRESSED_READ  (68),
		.IN_PKT_BURSTWRAP_H            (79),
		.IN_PKT_BURSTWRAP_L            (79),
		.IN_PKT_BURST_SIZE_H           (82),
		.IN_PKT_BURST_SIZE_L           (80),
		.IN_PKT_RESPONSE_STATUS_H      (100),
		.IN_PKT_RESPONSE_STATUS_L      (99),
		.IN_PKT_TRANS_EXCLUSIVE        (73),
		.IN_PKT_BURST_TYPE_H           (84),
		.IN_PKT_BURST_TYPE_L           (83),
		.IN_PKT_ORI_BURST_SIZE_L       (101),
		.IN_PKT_ORI_BURST_SIZE_H       (103),
		.IN_ST_DATA_W                  (104),
		.OUT_PKT_ADDR_H                (175),
		.OUT_PKT_ADDR_L                (144),
		.OUT_PKT_DATA_H                (127),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (143),
		.OUT_PKT_BYTEEN_L              (128),
		.OUT_PKT_BYTE_CNT_H            (186),
		.OUT_PKT_BYTE_CNT_L            (182),
		.OUT_PKT_TRANS_COMPRESSED_READ (176),
		.OUT_PKT_BURST_SIZE_H          (190),
		.OUT_PKT_BURST_SIZE_L          (188),
		.OUT_PKT_RESPONSE_STATUS_H     (208),
		.OUT_PKT_RESPONSE_STATUS_L     (207),
		.OUT_PKT_TRANS_EXCLUSIVE       (181),
		.OUT_PKT_BURST_TYPE_H          (192),
		.OUT_PKT_BURST_TYPE_L          (191),
		.OUT_PKT_ORI_BURST_SIZE_L      (209),
		.OUT_PKT_ORI_BURST_SIZE_H      (211),
		.OUT_ST_DATA_W                 (212),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1)
	) width_adapter (
		.clk                  (pll_0_outclk0_clk),                                   //       clk.clk
		.reset                (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (rsp_xbar_mux_001_src_valid),                          //      sink.valid
		.in_channel           (rsp_xbar_mux_001_src_channel),                        //          .channel
		.in_startofpacket     (rsp_xbar_mux_001_src_startofpacket),                  //          .startofpacket
		.in_endofpacket       (rsp_xbar_mux_001_src_endofpacket),                    //          .endofpacket
		.in_ready             (rsp_xbar_mux_001_src_ready),                          //          .ready
		.in_data              (rsp_xbar_mux_001_src_data),                           //          .data
		.out_endofpacket      (width_adapter_src_endofpacket),                       //       src.endofpacket
		.out_data             (width_adapter_src_data),                              //          .data
		.out_channel          (width_adapter_src_channel),                           //          .channel
		.out_valid            (width_adapter_src_valid),                             //          .valid
		.out_ready            (width_adapter_src_ready),                             //          .ready
		.out_startofpacket    (width_adapter_src_startofpacket),                     //          .startofpacket
		.in_command_size_data (3'b000)                                               // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (175),
		.IN_PKT_ADDR_L                 (144),
		.IN_PKT_DATA_H                 (127),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (143),
		.IN_PKT_BYTEEN_L               (128),
		.IN_PKT_BYTE_CNT_H             (186),
		.IN_PKT_BYTE_CNT_L             (182),
		.IN_PKT_TRANS_COMPRESSED_READ  (176),
		.IN_PKT_BURSTWRAP_H            (187),
		.IN_PKT_BURSTWRAP_L            (187),
		.IN_PKT_BURST_SIZE_H           (190),
		.IN_PKT_BURST_SIZE_L           (188),
		.IN_PKT_RESPONSE_STATUS_H      (208),
		.IN_PKT_RESPONSE_STATUS_L      (207),
		.IN_PKT_TRANS_EXCLUSIVE        (181),
		.IN_PKT_BURST_TYPE_H           (192),
		.IN_PKT_BURST_TYPE_L           (191),
		.IN_PKT_ORI_BURST_SIZE_L       (209),
		.IN_PKT_ORI_BURST_SIZE_H       (211),
		.IN_ST_DATA_W                  (212),
		.OUT_PKT_ADDR_H                (67),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (78),
		.OUT_PKT_BYTE_CNT_L            (74),
		.OUT_PKT_TRANS_COMPRESSED_READ (68),
		.OUT_PKT_BURST_SIZE_H          (82),
		.OUT_PKT_BURST_SIZE_L          (80),
		.OUT_PKT_RESPONSE_STATUS_H     (100),
		.OUT_PKT_RESPONSE_STATUS_L     (99),
		.OUT_PKT_TRANS_EXCLUSIVE       (73),
		.OUT_PKT_BURST_TYPE_H          (84),
		.OUT_PKT_BURST_TYPE_L          (83),
		.OUT_PKT_ORI_BURST_SIZE_L      (101),
		.OUT_PKT_ORI_BURST_SIZE_H      (103),
		.OUT_ST_DATA_W                 (104),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1)
	) width_adapter_001 (
		.clk                  (pll_0_outclk0_clk),                                   //       clk.clk
		.reset                (hps_to_plasma_dma_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (addr_router_001_src_valid),                           //      sink.valid
		.in_channel           (addr_router_001_src_channel),                         //          .channel
		.in_startofpacket     (addr_router_001_src_startofpacket),                   //          .startofpacket
		.in_endofpacket       (addr_router_001_src_endofpacket),                     //          .endofpacket
		.in_ready             (addr_router_001_src_ready),                           //          .ready
		.in_data              (addr_router_001_src_data),                            //          .data
		.out_endofpacket      (width_adapter_001_src_endofpacket),                   //       src.endofpacket
		.out_data             (width_adapter_001_src_data),                          //          .data
		.out_channel          (width_adapter_001_src_channel),                       //          .channel
		.out_valid            (width_adapter_001_src_valid),                         //          .valid
		.out_ready            (width_adapter_001_src_ready),                         //          .ready
		.out_startofpacket    (width_adapter_001_src_startofpacket),                 //          .startofpacket
		.in_command_size_data (3'b000)                                               // (terminated)
	);

endmodule
