	de1_soc u0 (
		.clk_clk                             (<connected-to-clk_clk>),                             //                          clk.clk
		.hex_0_external_connection_export    (<connected-to-hex_0_external_connection_export>),    //    hex_0_external_connection.export
		.hex_1_external_connection_export    (<connected-to-hex_1_external_connection_export>),    //    hex_1_external_connection.export
		.hex_2_external_connection_export    (<connected-to-hex_2_external_connection_export>),    //    hex_2_external_connection.export
		.hex_3_external_connection_export    (<connected-to-hex_3_external_connection_export>),    //    hex_3_external_connection.export
		.hex_4_external_connection_export    (<connected-to-hex_4_external_connection_export>),    //    hex_4_external_connection.export
		.hex_5_external_connection_export    (<connected-to-hex_5_external_connection_export>),    //    hex_5_external_connection.export
		.hps_0_ddr_mem_a                     (<connected-to-hps_0_ddr_mem_a>),                     //                    hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                    (<connected-to-hps_0_ddr_mem_ba>),                    //                             .mem_ba
		.hps_0_ddr_mem_ck                    (<connected-to-hps_0_ddr_mem_ck>),                    //                             .mem_ck
		.hps_0_ddr_mem_ck_n                  (<connected-to-hps_0_ddr_mem_ck_n>),                  //                             .mem_ck_n
		.hps_0_ddr_mem_cke                   (<connected-to-hps_0_ddr_mem_cke>),                   //                             .mem_cke
		.hps_0_ddr_mem_cs_n                  (<connected-to-hps_0_ddr_mem_cs_n>),                  //                             .mem_cs_n
		.hps_0_ddr_mem_ras_n                 (<connected-to-hps_0_ddr_mem_ras_n>),                 //                             .mem_ras_n
		.hps_0_ddr_mem_cas_n                 (<connected-to-hps_0_ddr_mem_cas_n>),                 //                             .mem_cas_n
		.hps_0_ddr_mem_we_n                  (<connected-to-hps_0_ddr_mem_we_n>),                  //                             .mem_we_n
		.hps_0_ddr_mem_reset_n               (<connected-to-hps_0_ddr_mem_reset_n>),               //                             .mem_reset_n
		.hps_0_ddr_mem_dq                    (<connected-to-hps_0_ddr_mem_dq>),                    //                             .mem_dq
		.hps_0_ddr_mem_dqs                   (<connected-to-hps_0_ddr_mem_dqs>),                   //                             .mem_dqs
		.hps_0_ddr_mem_dqs_n                 (<connected-to-hps_0_ddr_mem_dqs_n>),                 //                             .mem_dqs_n
		.hps_0_ddr_mem_odt                   (<connected-to-hps_0_ddr_mem_odt>),                   //                             .mem_odt
		.hps_0_ddr_mem_dm                    (<connected-to-hps_0_ddr_mem_dm>),                    //                             .mem_dm
		.hps_0_ddr_oct_rzqin                 (<connected-to-hps_0_ddr_oct_rzqin>),                 //                             .oct_rzqin
		.plasma_soc_0_leds_ld                (<connected-to-plasma_soc_0_leds_ld>),                //            plasma_soc_0_leds.ld
		.plasma_soc_0_sd_card_spi_cs         (<connected-to-plasma_soc_0_sd_card_spi_cs>),         //         plasma_soc_0_sd_card.spi_cs
		.plasma_soc_0_sd_card_spi_miso       (<connected-to-plasma_soc_0_sd_card_spi_miso>),       //                             .spi_miso
		.plasma_soc_0_sd_card_spi_mosi       (<connected-to-plasma_soc_0_sd_card_spi_mosi>),       //                             .spi_mosi
		.plasma_soc_0_sd_card_spi_sclk       (<connected-to-plasma_soc_0_sd_card_spi_sclk>),       //                             .spi_sclk
		.plasma_soc_0_switches_sw            (<connected-to-plasma_soc_0_switches_sw>),            //        plasma_soc_0_switches.sw
		.plasma_soc_0_uart_uart_rx           (<connected-to-plasma_soc_0_uart_uart_rx>),           //            plasma_soc_0_uart.uart_rx
		.plasma_soc_0_uart_uart_tx           (<connected-to-plasma_soc_0_uart_uart_tx>),           //                             .uart_tx
		.sdram_controller_0_wire_addr        (<connected-to-sdram_controller_0_wire_addr>),        //      sdram_controller_0_wire.addr
		.sdram_controller_0_wire_ba          (<connected-to-sdram_controller_0_wire_ba>),          //                             .ba
		.sdram_controller_0_wire_cas_n       (<connected-to-sdram_controller_0_wire_cas_n>),       //                             .cas_n
		.sdram_controller_0_wire_cke         (<connected-to-sdram_controller_0_wire_cke>),         //                             .cke
		.sdram_controller_0_wire_cs_n        (<connected-to-sdram_controller_0_wire_cs_n>),        //                             .cs_n
		.sdram_controller_0_wire_dq          (<connected-to-sdram_controller_0_wire_dq>),          //                             .dq
		.sdram_controller_0_wire_dqm         (<connected-to-sdram_controller_0_wire_dqm>),         //                             .dqm
		.sdram_controller_0_wire_ras_n       (<connected-to-sdram_controller_0_wire_ras_n>),       //                             .ras_n
		.sdram_controller_0_wire_we_n        (<connected-to-sdram_controller_0_wire_we_n>),        //                             .we_n
		.switches_external_connection_export (<connected-to-switches_external_connection_export>), // switches_external_connection.export
		.sys_sdram_pll_0_sdram_clk_clk       (<connected-to-sys_sdram_pll_0_sdram_clk_clk>)        //    sys_sdram_pll_0_sdram_clk.clk
	);

